name: CI-CD-Pipeline-to-AWS-ElasticBeastalk

on:
  push:
    branches: 
      - master


jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1
