name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BACKET_NAME: "flask-applicarion-package-DHK24"
  EB_APPLICATION_NAME: "MyFlaskEB"
  EB_ENVIROMENT_NAME: "MyFlaskEB-env"
  DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha}}.zip"
  AWS_REGION_NAME: "us-east-1"

on:
  push:
    branches: 
      - master


jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1

      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
        
        
