name: CI-CD-Pipeline-to-AWS-ElasticBeastalk
env:
  EB_PACKAGE_S3_BACKET_NAME: "flask-applicarion-package-t23i4"
  EB_APPLICATION_NAME: "MyFlaskEB"
  EB_ENVIROMENT_NAME: "MyFlaskeb-env"
  DEPLOY_PACKAGE_NAME: "flask_app_${{ github.sha}}.zip"
  AWS_REGION_NAME: "us-east-1"

on:
  push:
    branches: 
      - master


jobs:
  my_ci_part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone our repo
        uses: actions/checkout@v1

      - name: Create ZIP deployment package
        run: zip -r ${{ env.DEPLOY_PACKAGE_NAME}} ./ -x *.git*
        
      - name: Configure my AWS credentional
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
      
      - name: Copy deployment packege to S3 bucket
        run: aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BACKET_NAME }}/
        
  my_cd_part:
    runs-on: ubuntu-latest
    needs: [my_ci_part] 
    
    steps:
      - name: Configure my AWS credentional
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id     : ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
          
      - name: Create new EB application
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APPLICATION_NAME }} \
          --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BACKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
          --version-label "Ver-${{ github.sha }}" \
          --description "Commit SHA ${{ github.sha }}"  
          
      - name: Deploy new EB application version
        run: aws elasticbeanstalk update-enviroment --enviroment-name ${{ env.EB_ENVIROMENT_NAME }} --version-label "Ver-${{ github.sha }}"   
          
          
          
          
          
          
          
          
          
